name: "Build JOSS Paper Draft"

on:
  push:
    paths:
      - joss/**
      - .github/workflows/draft-pdf.yml

jobs:
  build-paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install LaTeX and Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended \
            texlive-fonts-extra texlive-latex-extra pandoc

      - name: Compile JOSS paper to PDF
        run: |
          cd joss
          pandoc paper.md --from markdown --to pdf \
            --citeproc --bibliography=paper.bib \
            --output=paper.pdf

      - name: Upload paper
        uses: actions/upload-artifact@v4
        with:
          name: joss-paper
          path: joss/paper.pdf
